[server]
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
headless = true
enableXsrfProtection = false
runOnSave = true
address = "0.0.0.0"
port = 9441
fileWatcherType = "auto"
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true
enumCoercion = "nameAndValue" #"nameOnly"


[logger]
level = "error"


[theme]
base                     = "light"
primaryColor             = "#00a84a"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#FAF5F0"
textColor                = "#000000"
font                     = "sans serif"

