[server]
headless              = false
enableCORS            = true
port                  = 5000
address               = "0.0.0.0"
enableXsrfProtection  = false
runOnSave             = true

[theme]
base                     = "light"
primaryColor             = "#70587C"
backgroundColor          = "#C8B8DB"
secondaryBackgroundColor = "#502F4C"
textColor                = "#000000"
font                     = "sans serif"

[logger]
level = "info"

