[server]
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
headless = true
enableXsrfProtection = false
runOnSave = true
port = 8501
fileWatcherType = "auto"
enableWebsocketCompression = false
#disconnectedSessionTTL = 120

[theme]
base                     = "light"
primaryColor             = "#B06E2E"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#FAF5F0"
textColor                = "#000000"
font                     = "sans serif"

